-- MySQL Script generated by MySQL Workbench
-- Wed Jul  9 16:30:20 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_usuario` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `tipo_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `tipo` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `tipo_idx` (`tipo` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `tipo`
    FOREIGN KEY (`tipo`)
    REFERENCES `mydb`.`tipo_usuario` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_log` (
  `id_tipo_log` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_log`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`local` (
  `id_local` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_local`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ordem_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ordem_servico` (
  `id_ordem_servico` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `tecnico` INT NOT NULL,
  `prazo` DATE NOT NULL,
  `urgencia` ENUM('baixa', 'média', 'alta') NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `local_id_local` INT NOT NULL,
  PRIMARY KEY (`id_ordem_servico`),
  INDEX `tecnico_idx` (`tecnico` ASC) VISIBLE,
  INDEX `fk_ordem_servico_local1_idx` (`local_id_local` ASC) VISIBLE,
  CONSTRAINT `tecnico`
    FOREIGN KEY (`tecnico`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_servico_local1`
    FOREIGN KEY (`local_id_local`)
    REFERENCES `mydb`.`local` (`id_local`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`periodicidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`periodicidade` (
  `id_periodicidade` INT NOT NULL AUTO_INCREMENT,
  `tipo_periodicidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_periodicidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`manutencao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`manutencao` (
  `id_manutencao` INT NOT NULL AUTO_INCREMENT,
  `tipo_manutencao` ENUM('Preditiva', 'Preventiva', 'Corretiva') NOT NULL,
  `ordem_servico_id_ordem_servico` INT NOT NULL,
  `local_id_local` INT NOT NULL,
  `periodicidade_id_periodicidade` INT NOT NULL,
  PRIMARY KEY (`id_manutencao`),
  INDEX `fk_manutencao_ordem_servico1_idx` (`ordem_servico_id_ordem_servico` ASC) VISIBLE,
  INDEX `fk_manutencao_local1_idx` (`local_id_local` ASC) VISIBLE,
  INDEX `fk_manutencao_periodicidade1_idx` (`periodicidade_id_periodicidade` ASC) VISIBLE,
  CONSTRAINT `fk_manutencao_ordem_servico1`
    FOREIGN KEY (`ordem_servico_id_ordem_servico`)
    REFERENCES `mydb`.`ordem_servico` (`id_ordem_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manutencao_local1`
    FOREIGN KEY (`local_id_local`)
    REFERENCES `mydb`.`local` (`id_local`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manutencao_periodicidade1`
    FOREIGN KEY (`periodicidade_id_periodicidade`)
    REFERENCES `mydb`.`periodicidade` (`id_periodicidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`log` (
  `id_log` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NULL,
  `hora` TIME NULL,
  `tipo` INT NULL,
  `descricao` VARCHAR(45) NULL,
  `tipo_log_id_tipo_log` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `ordem_servico_id_ordem_servico` INT NULL,
  `manutencao_id_manutencao` INT NULL,
  PRIMARY KEY (`id_log`),
  INDEX `fk_log_tipo_log1_idx` (`tipo_log_id_tipo_log` ASC) VISIBLE,
  INDEX `fk_log_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_log_ordem_servico1_idx` (`ordem_servico_id_ordem_servico` ASC) VISIBLE,
  INDEX `fk_log_manutencao1_idx` (`manutencao_id_manutencao` ASC) VISIBLE,
  CONSTRAINT `fk_log_tipo_log1`
    FOREIGN KEY (`tipo_log_id_tipo_log`)
    REFERENCES `mydb`.`tipo_log` (`id_tipo_log`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_log_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_log_ordem_servico1`
    FOREIGN KEY (`ordem_servico_id_ordem_servico`)
    REFERENCES `mydb`.`ordem_servico` (`id_ordem_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_log_manutencao1`
    FOREIGN KEY (`manutencao_id_manutencao`)
    REFERENCES `mydb`.`manutencao` (`id_manutencao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_ativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_ativo` (
  `id_tipo_ativo` INT NOT NULL AUTO_INCREMENT,
  `nome_tipo_ativo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_ativo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ativos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ativos` (
  `id_ativos` INT NOT NULL AUTO_INCREMENT,
  `modelo_ativo` VARCHAR(45) NOT NULL,
  `ultima_manutencao` DATE NULL,
  `data_instalacao` DATE NULL,
  `descricao` VARCHAR(45) NULL,
  `local_id_local` INT NOT NULL,
  `tipo_ativo_id_tipo_ativo` INT NOT NULL,
  `periodicidade_id_periodicidade` INT NOT NULL,
  PRIMARY KEY (`id_ativos`),
  INDEX `fk_ativos_local1_idx` (`local_id_local` ASC) VISIBLE,
  INDEX `fk_ativos_tipo_ativo1_idx` (`tipo_ativo_id_tipo_ativo` ASC) VISIBLE,
  INDEX `fk_ativos_periodicidade1_idx` (`periodicidade_id_periodicidade` ASC) VISIBLE,
  CONSTRAINT `fk_ativos_local1`
    FOREIGN KEY (`local_id_local`)
    REFERENCES `mydb`.`local` (`id_local`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ativos_tipo_ativo1`
    FOREIGN KEY (`tipo_ativo_id_tipo_ativo`)
    REFERENCES `mydb`.`tipo_ativo` (`id_tipo_ativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ativos_periodicidade1`
    FOREIGN KEY (`periodicidade_id_periodicidade`)
    REFERENCES `mydb`.`periodicidade` (`id_periodicidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
