/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.loggers.view;

import br.com.loggers.controller.Controller;
import br.com.loggers.controller.Log;
import br.com.loggers.controller.Manutencao;
import br.com.loggers.controller.OS;
import br.com.loggers.controller.User;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import java.io.IOException;
import java.io.InputStream;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.text.AbstractDocument;
import popup.glasspanepopup.GlassPanePopup;


/**
 *
 * @author Aluno
 */
public class ManutencaoForms extends javax.swing.JPanel {
    /**
     * Creates new form PopupView
     */
    
    User logged;
    
    public ManutencaoForms(User logged) {
        initComponents();
        setOpaque(false);
        
        this.logged = logged;
        
        Controller controller = new Controller();
        
        List<String> categoriesOS = controller.getOSID();
        for (String name : categoriesOS) {
            jComboBox1.addItem(name);
        }
        
        List<String> categoriesPeriodicidade = controller.getPeriodicidade();
        for (String name : categoriesPeriodicidade) {
            jComboBox7.addItem(name);
        }
        List<String> locais = controller.getLocal();
        for (String name : locais) {
            jComboBox4.addItem(name);
        }
    }
    private boolean verificarCampos() {
    if (jComboBox1.getSelectedItem() == null ||
        jComboBox6.getSelectedItem() == null ||
        jComboBox4.getSelectedItem() == null ||
        jComboBox7.getSelectedItem() == null ||
        jTextArea1.getText().trim().isEmpty()) {
        
        
        return false;
    }
    return true;
    }
    
    
    @Override
    protected void paintComponent(Graphics grphcs) {
        
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        g2.dispose();
        super.paintComponent(grphcs);
    }
    
    public static Font carregarFonte(int estilo, float tamanho) {
    try {
        String caminhoFonte;

        switch (estilo) {
            case Font.BOLD:
                caminhoFonte = "/resources/fonts/Poppins-Bold.ttf";
                break;
            default:
                caminhoFonte = "/resources/fonts/Poppins-Medium.ttf";
                break;
        }

        InputStream is = View.class.getResourceAsStream(caminhoFonte);
        Font fonteBase = Font.createFont(Font.TRUETYPE_FONT, is);
        return fonteBase.deriveFont(estilo, tamanho);

    } catch (FontFormatException | IOException | NullPointerException e) {
        e.printStackTrace();
        return new JLabel().getFont(); // fallback: fonte padrão do Swing
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(791, 554));
        setPreferredSize(new java.awt.Dimension(791, 554));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(carregarFonte(Font.BOLD, 28));
        jLabel1.setText("Registrar Manutenção");
        jLabel1.setMaximumSize(new java.awt.Dimension(142316, 42316));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 35, -1, -1));

        jLabel2.setFont(carregarFonte(Font.PLAIN, 15));
        jLabel2.setText("Preencha os campos abaixos para registrar uma manutenção.");
        jLabel2.setMaximumSize(new java.awt.Dimension(334223, 1623));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 85, -1, -1));

        jLabel3.setFont(carregarFonte(Font.PLAIN, 15));
        jLabel3.setText("ID da ordem de serviço");
        jLabel3.setMaximumSize(new java.awt.Dimension(333, 1336));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 140, -1, -1));

        jLabel4.setFont(carregarFonte(Font.PLAIN, 15));
        jLabel4.setText("Local");
        jLabel4.setMaximumSize(new java.awt.Dimension(3333, 1336));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 240, -1, -1));

        jComboBox1.setFont(carregarFonte(Font.PLAIN, 14));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 170, 336, 45));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Vector_1.png"))); // NOI18N
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 50, 45));

        jLabel6.setFont(carregarFonte(Font.PLAIN, 15));
        jLabel6.setText("Descrição");
        jLabel6.setMaximumSize(new java.awt.Dimension(343, 1643));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(carregarFonte(Font.PLAIN, 14));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 700, 110));

        jButton3.setBackground(new java.awt.Color(217, 217, 217));
        jButton3.setFont(carregarFonte(Font.BOLD, 16));
        jButton3.setText("Cancelar");
        jButton3.setPreferredSize(new java.awt.Dimension(107, 42));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, -1, -1));

        jButton5.setBackground(new java.awt.Color(60, 137, 166));
        jButton5.setFont(carregarFonte(Font.BOLD, 16));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Salvar");
        jButton5.setPreferredSize(new java.awt.Dimension(107, 42));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, -1, -1));

        jComboBox4.setFont(carregarFonte(Font.PLAIN, 14));
        add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 270, 283, 45));

        jComboBox6.setFont(carregarFonte(Font.PLAIN, 14));
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Preditiva", "Preventiva", "Corretiva" }));
        add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 336, 45));

        jLabel10.setFont(carregarFonte(Font.PLAIN, 15));
        jLabel10.setText("Tipo de manutenção");
        jLabel10.setMaximumSize(new java.awt.Dimension(3333, 2330));
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        jComboBox7.setFont(carregarFonte(Font.PLAIN, 14));
        add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 336, 45));

        jLabel11.setFont(carregarFonte(Font.PLAIN, 15));
        jLabel11.setText("Periodicidade De Manutenção");
        jLabel11.setMaximumSize(new java.awt.Dimension(13359, 1336));
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        GlassPanePopup.closePopupLast();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(!verificarCampos()){
            GlassPanePopup.showPopup(new PopupView("Erro!", "Um ou mais campos obrigatórios não foram preenchidos."));
        }
        else{
            Controller controller = new Controller();
            
            int periodicidade_id_periodicidade = controller.getPeriocididadeID(jComboBox7.getSelectedItem().toString());
            int local_id_local = controller.getLocalId(jComboBox4.getSelectedItem().toString());
            String tipo_manutencao = jComboBox6.getSelectedItem().toString();
            int ordem_servico_id_ordem_servico = Integer.parseInt((String) jComboBox1.getSelectedItem());
            
            Manutencao manutencao = new Manutencao(tipo_manutencao, ordem_servico_id_ordem_servico, local_id_local, periodicidade_id_periodicidade);
            
           
            try {
                controller.insertManutencao(manutencao);
                GlassPanePopup.showPopup(new PopupView("Manutenção registrada!", "A manutenção foi registrada com sucesso!"));
            }
            catch(Exception e) {
                GlassPanePopup.showPopup(new PopupView("Erro!", "A nova manutenção não pôde ser registrada!"));
              
            }
            //insert log
            LocalDate data = LocalDate.now();
            LocalTime hora = LocalTime.now();
            int tipo = 1;
            int tipo_log_id_tipo_log = 1;
            int usuario_id_usuario = logged.getId_usuario();
            int manutencao_id_manutencao = 1;
            String descricaoLog = "Adicionar manutenção";
            
            Log log = new Log(data, hora, tipo, tipo_log_id_tipo_log, usuario_id_usuario, 1, manutencao_id_manutencao, descricaoLog);
            controller.insertLogManut(log);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

// Variables declaration - do not modify                     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
