/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.loggers.view;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JLabel;
import popup.glasspanepopup.GlassPanePopup;


/**
 *
 * @author Aluno
 */
public class Notificacao extends javax.swing.JPanel {
    
    public String title, text;

    public JLabel getjLabel1() {
        return jLabelTitle;
    }

    /**
     * Creates new form PopupView
     */
    public Notificacao() {
        initComponents();
        setOpaque(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jLabelText = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(791, 666));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(60, 137, 166));
        jButton5.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("FECHAR");
        jButton5.setAlignmentX(0.5F);
        jButton5.setMaximumSize(new java.awt.Dimension(94, 42));
        jButton5.setMinimumSize(new java.awt.Dimension(94, 42));
        jButton5.setPreferredSize(new java.awt.Dimension(107, 42));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 600, -1, -1));

        jLabelTitle.setFont(new java.awt.Font("Poppins", 1, 28)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTitle.setText("Notificações");
        jLabelTitle.setAlignmentX(0.5F);
        jLabelTitle.setPreferredSize(new java.awt.Dimension(500, 43));
        add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabelText.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jLabelText.setText("Nenhuma notificação");
        jLabelText.setAlignmentY(0.4F);
        add(jLabelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        GlassPanePopup.closePopupLast();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    public JLabel getjLabelText() {
        return jLabelText;
    }

    public JLabel getjLabelTitle() {
        return jLabelTitle;
    }
// Variables declaration - do not modify                     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabelText;
    private javax.swing.JLabel jLabelTitle;
    // End of variables declaration//GEN-END:variables
}
