/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.loggers.view;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.JLabel;
import popup.glasspanepopup.GlassPanePopup;


/**
 *
 * @author Aluno
 */
public class Notificacao extends javax.swing.JPanel {
    
    public String title, text;

    public JLabel getjLabel1() {
        return jLabelTitle;
    }

    /**
     * Creates new form PopupView
     */
    public Notificacao() {
        initComponents();
        setOpaque(false);
    }
    
    
    @Override
    protected void paintComponent(Graphics grphcs) {
        
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        g2.dispose();
        super.paintComponent(grphcs);
    }
    
    public static Font carregarFonte(int estilo, float tamanho) {
    try {
        String caminhoFonte;

        switch (estilo) {
            case Font.BOLD:
                caminhoFonte = "/resources/fonts/Poppins-Bold.ttf";
                break;
            default:
                caminhoFonte = "/resources/fonts/Poppins-Medium.ttf";
                break;
        }

        InputStream is = View.class.getResourceAsStream(caminhoFonte);
        Font fonteBase = Font.createFont(Font.TRUETYPE_FONT, is);
        return fonteBase.deriveFont(estilo, tamanho);

    } catch (FontFormatException | IOException | NullPointerException e) {
        e.printStackTrace();
        return new JLabel().getFont(); // fallback: fonte padrão do Swing
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jLabelText = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(791, 242));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(60, 137, 166));
        jButton5.setFont(carregarFonte(Font.BOLD, 16));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("FECHAR");
        jButton5.setAlignmentX(0.5F);
        jButton5.setMaximumSize(new java.awt.Dimension(94, 42));
        jButton5.setMinimumSize(new java.awt.Dimension(94, 42));
        jButton5.setPreferredSize(new java.awt.Dimension(107, 42));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, -1, -1));

        jLabelTitle.setFont(carregarFonte(Font.BOLD, 28));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTitle.setText("Notificações");
        jLabelTitle.setAlignmentX(0.5F);
        jLabelTitle.setMaximumSize(new java.awt.Dimension(43266, 16423));
        jLabelTitle.setPreferredSize(new java.awt.Dimension(500, 43));
        add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabelText.setFont(carregarFonte(Font.PLAIN, 15));
        jLabelText.setText("Nenhuma notificação");
        jLabelText.setAlignmentY(0.4F);
        jLabelText.setMaximumSize(new java.awt.Dimension(143215, 1326));
        add(jLabelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        GlassPanePopup.closePopupLast();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    public JLabel getjLabelText() {
        return jLabelText;
    }

    public JLabel getjLabelTitle() {
        return jLabelTitle;
    }
// Variables declaration - do not modify                     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabelText;
    private javax.swing.JLabel jLabelTitle;
    // End of variables declaration//GEN-END:variables
}
