/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.loggers.view;

import br.com.loggers.controller.Controller;
import br.com.loggers.controller.Log;
import br.com.loggers.controller.OS;
import br.com.loggers.controller.User;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import java.io.IOException;
import java.io.InputStream;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JLabel;
import popup.glasspanepopup.GlassPanePopup;


/**
 *
 * @author Aluno
 */
public class OSForms extends javax.swing.JPanel {
    /**
     * Creates new form PopupView
     */
    User logged;
    public OSForms(User logged) {
        initComponents();
        setOpaque(false);
        
        this.logged = logged;
        
        Controller controller = new Controller();
        List<String> categories = controller.getTecnico();
        for (String name : categories) {
            jComboBox2.addItem(name);
        }
        
        List<String> locais = controller.getLocal();
        for (String name : locais) {
            jComboBox1.addItem(name);
        }
    }
    private boolean verificarCampos() {
    if (jTextField1.getText().trim().isEmpty() ||
        jComboBox1.getSelectedItem() == null ||
        jComboBox2.getSelectedItem() == null ||
        jComboBox3.getSelectedItem() == null ||
        jComboBoxYear.getSelectedItem() == null ||
        jComboBox5.getSelectedItem() == null ||
        jTextArea1.getText().trim().isEmpty()) {
        
        
        return false;
    }
    return true;
    }
    
    public static Font carregarFonte(int estilo, float tamanho) {
    try {
        String caminhoFonte;

        switch (estilo) {
            case Font.BOLD:
                caminhoFonte = "/resources/fonts/Poppins-Bold.ttf";
                break;
            default:
                caminhoFonte = "/resources/fonts/Poppins-Medium.ttf";
                break;
        }

        InputStream is = View.class.getResourceAsStream(caminhoFonte);
        Font fonteBase = Font.createFont(Font.TRUETYPE_FONT, is);
        return fonteBase.deriveFont(estilo, tamanho);

    } catch (FontFormatException | IOException | NullPointerException e) {
        e.printStackTrace();
        return new JLabel().getFont(); // fallback: fonte padrão do Swing
    }
}
    
    public static int converterMes(String mes) {
    switch (mes.toLowerCase()) {
        case "janeiro": return 1;
        case "fevereiro": return 2;
        case "março": return 3;
        case "abril": return 4;
        case "maio": return 5;
        case "junho": return 6;
        case "julho": return 7;
        case "agosto": return 8;
        case "setembro": return 9;
        case "outubro": return 10;
        case "novembro": return 11;
        case "dezembro": return 12;
        default: return -1;
    }
}
    
    @Override
    protected void paintComponent(Graphics grphcs) {
        
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        g2.dispose();
        super.paintComponent(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxYear = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBoxDay = new javax.swing.JComboBox<>();
        jComboBoxMonth = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(791, 666));
        setPreferredSize(new java.awt.Dimension(791, 666));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(carregarFonte(Font.BOLD, 28));
        jLabel1.setText("Registrar OS");
        jLabel1.setMaximumSize(new java.awt.Dimension(6324, 1623));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 35, -1, -1));

        jLabel2.setFont(carregarFonte(Font.PLAIN, 15));
        jLabel2.setText("Preencha os campos abaixos para registrar uma ordem de serviço.");
        jLabel2.setMaximumSize(new java.awt.Dimension(342327, 132326));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 85, -1, -1));

        jLabel3.setFont(carregarFonte(Font.PLAIN, 15));
        jLabel3.setText("Título");
        jLabel3.setMaximumSize(new java.awt.Dimension(321, 126));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 140, -1, -1));

        jTextField1.setFont(carregarFonte(Font.PLAIN, 14));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 170, 336, 45));

        jLabel4.setFont(carregarFonte(Font.PLAIN, 15));
        jLabel4.setText("Local");
        jLabel4.setMaximumSize(new java.awt.Dimension(2822, 1236));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 240, -1, -1));

        jComboBox1.setFont(carregarFonte(Font.PLAIN, 14));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 270, 283, 45));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Vector_1.png"))); // NOI18N
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 50, 45));

        jLabel5.setFont(carregarFonte(Font.PLAIN, 15));
        jLabel5.setText("Técnico Responsável");
        jLabel5.setMaximumSize(new java.awt.Dimension(113210, 12216));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Vector_1.png"))); // NOI18N
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 50, 45));

        jComboBox2.setFont(carregarFonte(Font.PLAIN, 14));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 283, 45));

        jLabel6.setFont(carregarFonte(Font.PLAIN, 15));
        jLabel6.setText("Descrição");
        jLabel6.setMaximumSize(new java.awt.Dimension(4443, 13436));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 440, -1, -1));

        jComboBox3.setFont(carregarFonte(Font.PLAIN, 14));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "baixa", "média", "alta" }));
        add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 370, 336, 45));

        jLabel7.setFont(carregarFonte(Font.PLAIN, 15));
        jLabel7.setText("Data");
        jLabel7.setMaximumSize(new java.awt.Dimension(234, 163));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        jComboBoxYear.setFont(carregarFonte(Font.PLAIN, 14));
        jComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035" }));
        jComboBoxYear.setSelectedIndex(25);
        jComboBoxYear.setToolTipText("");
        add(jComboBoxYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 130, 45));

        jComboBox5.setFont(carregarFonte(Font.PLAIN, 14));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pendente", "em andamento", "finalizado", "agendado" }));
        add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 336, 45));

        jLabel8.setFont(carregarFonte(Font.PLAIN, 15));
        jLabel8.setText("Status");
        jLabel8.setMaximumSize(new java.awt.Dimension(333, 1336));
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        jLabel9.setFont(carregarFonte(Font.PLAIN, 15));
        jLabel9.setText("Urgência");
        jLabel9.setMaximumSize(new java.awt.Dimension(437, 316));
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 340, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(carregarFonte(Font.PLAIN, 14));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 470, 700, 110));

        jButton3.setBackground(new java.awt.Color(217, 217, 217));
        jButton3.setFont(carregarFonte(Font.BOLD, 16));
        jButton3.setText("Cancelar");
        jButton3.setPreferredSize(new java.awt.Dimension(107, 42));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 600, -1, -1));

        jButton5.setBackground(new java.awt.Color(60, 137, 166));
        jButton5.setFont(carregarFonte(Font.BOLD, 16));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Salvar");
        jButton5.setPreferredSize(new java.awt.Dimension(107, 42));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 600, -1, -1));

        jComboBoxDay.setFont(carregarFonte(Font.PLAIN, 14));
        jComboBoxDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        add(jComboBoxDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 60, 45));

        jComboBoxMonth.setFont(carregarFonte(Font.PLAIN, 14));
        jComboBoxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "janeiro", "fevereiro", "março", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro" }));
        add(jComboBoxMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 120, 45));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        GlassPanePopup.closePopupLast();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(!verificarCampos()){
            GlassPanePopup.showPopup(new PopupView("Erro!", "Um ou mais campos obrigatórios não foram preenchidos."));
        }
        else{
            Controller controller = new Controller();
            String titulo = jTextField1.getText();
            int tecnico = controller.getUserId(jComboBox2.getSelectedItem().toString());
            int mesNumero = converterMes(jComboBoxMonth.getSelectedItem().toString());
            String dateString = String.format("%s-%02d-%02d",
                jComboBoxYear.getSelectedItem().toString(),
                mesNumero,
                Integer.parseInt(jComboBoxDay.getSelectedItem().toString())
               );

            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            LocalDate prazo = LocalDate.parse(dateString, formatter);
            
            String urgencia = jComboBox3.getSelectedItem().toString();
            String status = jComboBox5.getSelectedItem().toString();
            String descricao = jTextArea1.getText();
            
            int local_id_local = controller.getLocalId(jComboBox1.getSelectedItem().toString());
            
            OS ordem = new OS(titulo, urgencia, status, descricao, prazo, tecnico, local_id_local);
            
            
           
            try {
                controller.insertOS(ordem);
                GlassPanePopup.showPopup(new PopupView("Ordem de serviço registrada!", "A nova ordem de serviço foi registrada com sucesso!"));
            }
            catch(Exception e) {
                GlassPanePopup.showPopup(new PopupView("Erro!", "A nova ordem de serviço não pôde ser registrada!"));
              
            }
            //para enviar o log
            LocalDate data = LocalDate.now();
            LocalTime hora = LocalTime.now();
            int tipo = 1;
            int tipo_log_id_tipo_log = 1;
            int usuario_id_usuario = logged.getId_usuario();
            int ordem_servico_id_ordem_servico = controller.getOSId(titulo);
            String descricaoLog = "Adicionar ordem de serviço";
            
            Log log = new Log(data, hora, tipo, tipo_log_id_tipo_log, usuario_id_usuario, ordem_servico_id_ordem_servico, 1, descricaoLog);
            controller.insertLogOS(log);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

// Variables declaration - do not modify                     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBoxDay;
    private javax.swing.JComboBox<String> jComboBoxMonth;
    private javax.swing.JComboBox<String> jComboBoxYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
