/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.loggers.view;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.JLabel;
import popup.glasspanepopup.GlassPanePopup;


/**
 *
 * @author Aluno
 */
public class PopupView extends javax.swing.JPanel {
    
    public String title, text;

    public JLabel getjLabel1() {
        return jLabelTitle;
    }

    /**
     * Creates new form PopupView
     */
    public PopupView(String title, String text) {
        initComponents();
        this.title = title;
        this.text = text;
        getjLabelTitle().setText(this.title);
        getjLabelText().setText(this.text);
        setOpaque(false);
    }
    
    
    @Override
    protected void paintComponent(Graphics grphcs) {
        
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        g2.dispose();
        super.paintComponent(grphcs);
    }
    public static Font carregarFonte(int estilo, float tamanho) {
    try {
        String caminhoFonte;

        switch (estilo) {
            case Font.BOLD:
                caminhoFonte = "/resources/fonts/Poppins-Bold.ttf";
                break;
            default:
                caminhoFonte = "/resources/fonts/Poppins-Medium.ttf";
                break;
        }

        InputStream is = View.class.getResourceAsStream(caminhoFonte);
        Font fonteBase = Font.createFont(Font.TRUETYPE_FONT, is);
        return fonteBase.deriveFont(estilo, tamanho);

    } catch (FontFormatException | IOException | NullPointerException e) {
        e.printStackTrace();
        return new JLabel().getFont(); // fallback: fonte padrão do Swing
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelText = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(534, 188));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setPreferredSize(new java.awt.Dimension(534, 176));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(534, 40));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabelTitle.setFont(carregarFonte(Font.BOLD, 28));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTitle.setText("Erro!");
        jLabelTitle.setAlignmentX(0.5F);
        jLabelTitle.setMaximumSize(new java.awt.Dimension(123, 12136));
        jLabelTitle.setPreferredSize(new java.awt.Dimension(500, 43));
        jPanel1.add(jLabelTitle, java.awt.BorderLayout.WEST);

        jPanel5.add(jPanel1);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(474, 70));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabelText.setFont(carregarFonte(Font.PLAIN, 15));
        jLabelText.setText("<html>Um ou mais campos obrigatórios não foram preenchidos.<br><br></html>");
        jLabelText.setAlignmentY(0.4F);
        jLabelText.setMaximumSize(new java.awt.Dimension(2147483647, 3332));
        jPanel4.add(jLabelText, java.awt.BorderLayout.WEST);

        jPanel5.add(jPanel4);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jButton5.setBackground(new java.awt.Color(60, 137, 166));
        jButton5.setFont(carregarFonte(Font.BOLD, 16));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("FECHAR");
        jButton5.setAlignmentX(0.5F);
        jButton5.setMaximumSize(new java.awt.Dimension(94, 42));
        jButton5.setMinimumSize(new java.awt.Dimension(94, 42));
        jButton5.setPreferredSize(new java.awt.Dimension(107, 42));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, java.awt.BorderLayout.EAST);

        jPanel5.add(jPanel2);

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 23, 474, 134));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        GlassPanePopup.closePopupLast();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    public JLabel getjLabelText() {
        return jLabelText;
    }

    public JLabel getjLabelTitle() {
        return jLabelTitle;
    }
// Variables declaration - do not modify                     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabelText;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
