/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.loggers.view;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JLabel;
import popup.glasspanepopup.GlassPanePopup;


/**
 *
 * @author Aluno
 */
public class PopupView extends javax.swing.JPanel {
    
    public String title, text;

    public JLabel getjLabel1() {
        return jLabelTitle;
    }

    /**
     * Creates new form PopupView
     */
    public PopupView(String title, String text) {
        initComponents();
        this.title = title;
        this.text = text;
        getjLabelTitle().setText(this.title);
        getjLabelText().setText(this.text);
        setOpaque(false);
    }
    
    
    @Override
    protected void paintComponent(Graphics grphcs) {
        
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        g2.dispose();
        super.paintComponent(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

// Variables declaration - do not modify                     
    // Variables declaration - do not modify//GEN-BEGIN:variable
    // End of variables declaration//GEN-END:variables
}
