/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.loggers.view;


public class View extends javax.swing.JFrame {

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(View.class.getName());

    /**
     * Creates new form LoginView
     */
    public View() {
        
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane5 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        root = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        cadastro = new javax.swing.JPanel();
        jPanel59 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel60 = new javax.swing.JPanel();
        jPanel61 = new javax.swing.JPanel();
        jPanel62 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel63 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldEmail2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldEmail1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jPanel64 = new javax.swing.JPanel();
        jPasswordFieldSenha1 = new javax.swing.JPasswordField();
        jButton5 = new javax.swing.JButton();
        jPanel65 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        dashboard = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        nameUser = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        menu = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        ordem_servicoButton = new javax.swing.JButton();
        rootDashboard = new javax.swing.JPanel();
        ordem_servico = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel25 = new javax.swing.JPanel();

        jScrollPane5.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setSize(new java.awt.Dimension(1440, 810));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        root.setLayout(new java.awt.CardLayout());

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setPreferredSize(new java.awt.Dimension(1440, 810));
        login.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(23, 50, 62));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/server_image_svg.png"))); // NOI18N
        jPanel2.add(jLabel1, new java.awt.GridBagConstraints());

        login.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(540, 810));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(360, 384));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setAlignmentX(0.0F);
        jPanel5.setPreferredSize(new java.awt.Dimension(360, 80));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 28)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SGMP");
        jLabel2.setAlignmentX(0.5F);
        jLabel2.setPreferredSize(new java.awt.Dimension(81, 28));
        jPanel5.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("<html>Sistema de Gerenciamento<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;de Manutenção Predial</html>");
        jLabel3.setAlignmentX(0.5F);
        jPanel5.add(jLabel3);

        jPanel4.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(360, 186));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("E-mail");
        jLabel4.setFocusable(false);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel4.setPreferredSize(new java.awt.Dimension(49, 44));
        jPanel6.add(jLabel4);

        jTextFieldEmail.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jTextFieldEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldEmail.setAlignmentX(0.0F);
        jTextFieldEmail.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(java.awt.Color.decode("#D0D5DD"), 3, true),
            javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8)
        )
    );
    jTextFieldEmail.setPreferredSize(new java.awt.Dimension(360, 20));
    jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldEmailActionPerformed(evt);
        }
    });
    jPanel6.add(jTextFieldEmail);

    jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabel5.setText("Senha");
    jLabel5.setPreferredSize(new java.awt.Dimension(48, 44));
    jPanel6.add(jLabel5);

    jPanel9.setBackground(new java.awt.Color(255, 255, 255));
    jPanel9.setAlignmentX(0.0F);
    jPanel9.setPreferredSize(new java.awt.Dimension(360, 20));
    jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.X_AXIS));

    jPasswordFieldSenha.setFont(new java.awt.Font("Poppins", 1, 15)); // NOI18N
    jPasswordFieldSenha.setToolTipText("");
    jPasswordFieldSenha.setAlignmentX(0.0F);
    jPasswordFieldSenha.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(java.awt.Color.decode("#D0D5DD"), 3, true),
        javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8)
    )
    );
    jPasswordFieldSenha.setPreferredSize(new java.awt.Dimension(135, 20));
    jPanel9.add(jPasswordFieldSenha);

    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/eye.png"))); // NOI18N
    jButton3.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(java.awt.Color.decode("#D0D5DD"), 3, true),
        javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8)
    )
    );
    jButton3.setPreferredSize(new java.awt.Dimension(40, 30));
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });
    jPanel9.add(jButton3);

    jPanel6.add(jPanel9);

    jPanel4.add(jPanel6);

    jPanel7.setBackground(new java.awt.Color(255, 255, 255));
    jPanel7.setAlignmentX(0.0F);
    jPanel7.setPreferredSize(new java.awt.Dimension(360, 120));
    jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.PAGE_AXIS));

    jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel6.setText("<html> </html>");
    jLabel6.setAlignmentX(1.0F);
    jPanel7.add(jLabel6);

    jButton1.setBackground(new java.awt.Color(60, 137, 166));
    jButton1.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
    jButton1.setForeground(new java.awt.Color(255, 255, 255));
    jButton1.setText("Entrar");
    jButton1.setAlignmentX(1.0F);
    jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    jButton1.setMaximumSize(new java.awt.Dimension(360, 52));
    jButton1.setPreferredSize(new java.awt.Dimension(360, 52));
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    jPanel7.add(jButton1);

    jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel7.setText("<html></html>");
    jLabel7.setAlignmentX(1.0F);
    jPanel7.add(jLabel7);

    jButton2.setBackground(new java.awt.Color(60, 137, 166));
    jButton2.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
    jButton2.setForeground(new java.awt.Color(255, 255, 255));
    jButton2.setText("Cadastrar");
    jButton2.setAlignmentX(1.0F);
    jButton2.setBorderPainted(false);
    jButton2.setFocusPainted(false);
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });
    jPanel7.add(jButton2);

    jPanel4.add(jPanel7);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
            .addContainerGap(102, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(78, 78, 78))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap(209, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(217, Short.MAX_VALUE))
    );

    login.add(jPanel3, java.awt.BorderLayout.EAST);

    root.add(login, "login");

    cadastro.setBackground(new java.awt.Color(255, 255, 255));
    cadastro.setPreferredSize(new java.awt.Dimension(1440, 810));
    cadastro.setLayout(new java.awt.BorderLayout());

    jPanel59.setBackground(new java.awt.Color(23, 50, 62));
    jPanel59.setMinimumSize(new java.awt.Dimension(0, 0));
    jPanel59.setLayout(new java.awt.GridBagLayout());

    jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/server_image_svg.png"))); // NOI18N
    jPanel59.add(jLabel22, new java.awt.GridBagConstraints());

    cadastro.add(jPanel59, java.awt.BorderLayout.CENTER);

    jPanel60.setBackground(new java.awt.Color(255, 255, 255));
    jPanel60.setPreferredSize(new java.awt.Dimension(540, 810));

    jPanel61.setBackground(new java.awt.Color(255, 255, 255));
    jPanel61.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
    jPanel61.setPreferredSize(new java.awt.Dimension(360, 384));
    jPanel61.setLayout(new javax.swing.BoxLayout(jPanel61, javax.swing.BoxLayout.Y_AXIS));

    jPanel62.setBackground(new java.awt.Color(255, 255, 255));
    jPanel62.setAlignmentX(0.0F);
    jPanel62.setPreferredSize(new java.awt.Dimension(360, 80));
    jPanel62.setLayout(new javax.swing.BoxLayout(jPanel62, javax.swing.BoxLayout.Y_AXIS));

    jLabel23.setFont(new java.awt.Font("Poppins", 1, 28)); // NOI18N
    jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel23.setText("SGMP");
    jLabel23.setAlignmentX(0.5F);
    jLabel23.setPreferredSize(new java.awt.Dimension(81, 28));
    jPanel62.add(jLabel23);

    jLabel24.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
    jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel24.setText("<html>Sistema de Gerenciamento<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;de Manutenção Predial</html>");
    jLabel24.setAlignmentX(0.5F);
    jPanel62.add(jLabel24);

    jPanel61.add(jPanel62);

    jPanel63.setBackground(new java.awt.Color(255, 255, 255));
    jPanel63.setPreferredSize(new java.awt.Dimension(360, 180));
    jPanel63.setLayout(new javax.swing.BoxLayout(jPanel63, javax.swing.BoxLayout.Y_AXIS));

    jLabel27.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
    jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel27.setText("Nome");
    jLabel27.setFocusable(false);
    jLabel27.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
    jLabel27.setPreferredSize(new java.awt.Dimension(49, 44));
    jPanel63.add(jLabel27);

    jTextFieldEmail2.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
    jTextFieldEmail2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    jTextFieldEmail2.setAlignmentX(0.0F);
    jTextFieldEmail2.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(java.awt.Color.decode("#D0D5DD"), 3, true),
        javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8)
    )
    );
    jTextFieldEmail2.setPreferredSize(new java.awt.Dimension(360, 20));
    jTextFieldEmail2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldEmail2ActionPerformed(evt);
        }
    });
    jPanel63.add(jTextFieldEmail2);

    jLabel25.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
    jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel25.setText("E-mail");
    jLabel25.setFocusable(false);
    jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
    jLabel25.setPreferredSize(new java.awt.Dimension(49, 44));
    jPanel63.add(jLabel25);

    jTextFieldEmail1.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
    jTextFieldEmail1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    jTextFieldEmail1.setAlignmentX(0.0F);
    jTextFieldEmail1.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(java.awt.Color.decode("#D0D5DD"), 3, true),
        javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8)
    )
    );
    jTextFieldEmail1.setPreferredSize(new java.awt.Dimension(360, 20));
    jTextFieldEmail1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldEmail1ActionPerformed(evt);
        }
    });
    jPanel63.add(jTextFieldEmail1);

    jLabel26.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
    jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabel26.setText("Senha");
    jLabel26.setPreferredSize(new java.awt.Dimension(48, 44));
    jPanel63.add(jLabel26);

    jPanel64.setBackground(new java.awt.Color(255, 255, 255));
    jPanel64.setAlignmentX(0.0F);
    jPanel64.setPreferredSize(new java.awt.Dimension(360, 20));
    jPanel64.setLayout(new javax.swing.BoxLayout(jPanel64, javax.swing.BoxLayout.X_AXIS));

    jPasswordFieldSenha1.setFont(new java.awt.Font("Poppins", 1, 15)); // NOI18N
    jPasswordFieldSenha1.setToolTipText("");
    jPasswordFieldSenha1.setAlignmentX(0.0F);
    jPasswordFieldSenha1.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(java.awt.Color.decode("#D0D5DD"), 3, true),
        javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8)
    )
    );
    jPasswordFieldSenha1.setPreferredSize(new java.awt.Dimension(135, 20));
    jPanel64.add(jPasswordFieldSenha1);

    jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/eye.png"))); // NOI18N
    jButton5.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(java.awt.Color.decode("#D0D5DD"), 3, true),
        javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8)
    )
    );
    jButton5.setPreferredSize(new java.awt.Dimension(40, 30));
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
    });
    jPanel64.add(jButton5);

    jPanel63.add(jPanel64);

    jPanel61.add(jPanel63);

    jPanel65.setBackground(new java.awt.Color(255, 255, 255));
    jPanel65.setAlignmentX(0.0F);
    jPanel65.setPreferredSize(new java.awt.Dimension(360, 120));
    jPanel65.setLayout(new javax.swing.BoxLayout(jPanel65, javax.swing.BoxLayout.PAGE_AXIS));

    jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel30.setText("<html> </html>");
    jLabel30.setAlignmentX(1.0F);
    jPanel65.add(jLabel30);

    jButton7.setBackground(new java.awt.Color(60, 137, 166));
    jButton7.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
    jButton7.setForeground(new java.awt.Color(255, 255, 255));
    jButton7.setText("Cadastrar");
    jButton7.setAlignmentX(1.0F);
    jButton7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    jButton7.setMaximumSize(new java.awt.Dimension(360, 52));
    jButton7.setPreferredSize(new java.awt.Dimension(360, 52));
    jButton7.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton7ActionPerformed(evt);
        }
    });
    jPanel65.add(jButton7);

    jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel31.setText("<html></html>");
    jLabel31.setAlignmentX(1.0F);
    jPanel65.add(jLabel31);

    jButton8.setBackground(new java.awt.Color(60, 137, 166));
    jButton8.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
    jButton8.setForeground(new java.awt.Color(255, 255, 255));
    jButton8.setText("Voltar");
    jButton8.setAlignmentX(1.0F);
    jButton8.setBorderPainted(false);
    jButton8.setFocusPainted(false);
    jButton8.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton8ActionPerformed(evt);
        }
    });
    jPanel65.add(jButton8);

    jPanel61.add(jPanel65);

    javax.swing.GroupLayout jPanel60Layout = new javax.swing.GroupLayout(jPanel60);
    jPanel60.setLayout(jPanel60Layout);
    jPanel60Layout.setHorizontalGroup(
        jPanel60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel60Layout.createSequentialGroup()
            .addContainerGap(102, Short.MAX_VALUE)
            .addComponent(jPanel61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(78, 78, 78))
    );
    jPanel60Layout.setVerticalGroup(
        jPanel60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel60Layout.createSequentialGroup()
            .addContainerGap(174, Short.MAX_VALUE)
            .addComponent(jPanel61, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(169, Short.MAX_VALUE))
    );

    cadastro.add(jPanel60, java.awt.BorderLayout.EAST);

    root.add(cadastro, "cadastro");

    dashboard.setLayout(new java.awt.BorderLayout());

    header.setBackground(new java.awt.Color(60, 137, 166));
    header.setPreferredSize(new java.awt.Dimension(1440, 64));
    header.setLayout(new java.awt.BorderLayout());

    jLabel8.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(255, 255, 255));
    jLabel8.setText("SGMP");
    jLabel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
    header.add(jLabel8, java.awt.BorderLayout.LINE_START);

    jPanel1.setBackground(new java.awt.Color(60, 137, 166));
    jPanel1.setPreferredSize(new java.awt.Dimension(220, 100));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel17.setBackground(new java.awt.Color(60, 137, 166));
    jPanel17.setPreferredSize(new java.awt.Dimension(198, 32));
    jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.LINE_AXIS));

    nameUser.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
    nameUser.setForeground(new java.awt.Color(255, 255, 255));
    nameUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/user-3296.png"))); // NOI18N
    nameUser.setText("  Técnico - Mário");
    jPanel17.add(nameUser);

    jButton9.setBackground(new java.awt.Color(60, 137, 166));
    jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/chevron_down.png"))); // NOI18N
    jButton9.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
    jButton9.setBorderPainted(false);
    jButton9.setContentAreaFilled(false);
    jButton9.setFocusPainted(false);
    jPanel17.add(jButton9);

    jButton10.setBackground(new java.awt.Color(60, 137, 166));
    jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/notifica.png"))); // NOI18N
    jButton10.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
    jButton10.setBorderPainted(false);
    jButton10.setFocusPainted(false);
    jButton10.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton10ActionPerformed(evt);
        }
    });
    jPanel17.add(jButton10);

    jButton13.setBackground(new java.awt.Color(60, 137, 166));
    jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/notifica.png"))); // NOI18N
    jButton13.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
    jButton13.setBorderPainted(false);
    jButton13.setFocusPainted(false);
    jButton13.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton13ActionPerformed(evt);
        }
    });
    jPanel17.add(jButton13);

    jPanel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, 198, 32));

    header.add(jPanel1, java.awt.BorderLayout.LINE_END);

    dashboard.add(header, java.awt.BorderLayout.PAGE_START);

    menu.setBackground(new java.awt.Color(255, 255, 255));
    menu.setMinimumSize(new java.awt.Dimension(0, 0));
    menu.setPreferredSize(new java.awt.Dimension(263, 746));
    menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel10.setBackground(new java.awt.Color(255, 255, 255));
    jPanel10.setPreferredSize(new java.awt.Dimension(183, 256));
    jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.Y_AXIS));

    jPanel11.setBackground(new java.awt.Color(255, 255, 255));
    jPanel11.setMaximumSize(new java.awt.Dimension(2147483647, 42));
    jPanel11.setPreferredSize(new java.awt.Dimension(183, 42));
    jPanel11.setLayout(new java.awt.BorderLayout());

    jLabel9.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
    jLabel9.setText("Menu");
    jPanel11.add(jLabel9, java.awt.BorderLayout.LINE_START);

    jPanel10.add(jPanel11);

    jPanel12.setBackground(new java.awt.Color(255, 255, 255));
    jPanel12.setPreferredSize(new java.awt.Dimension(183, 42));

    ordem_servicoButton.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
    ordem_servicoButton.setForeground(new java.awt.Color(60, 137, 166));
    ordem_servicoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Chart.png"))); // NOI18N
    ordem_servicoButton.setText("  Ordens de Serviço");
    ordem_servicoButton.setBorderPainted(false);
    ordem_servicoButton.setFocusPainted(false);
    ordem_servicoButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    ordem_servicoButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            ordem_servicoButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
    jPanel12.setLayout(jPanel12Layout);
    jPanel12Layout.setHorizontalGroup(
        jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(ordem_servicoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel12Layout.setVerticalGroup(
        jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(ordem_servicoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
    );

    jPanel10.add(jPanel12);

    menu.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 220, 300));

    dashboard.add(menu, java.awt.BorderLayout.LINE_START);

    rootDashboard.setLayout(new java.awt.CardLayout());

    ordem_servico.setBackground(new java.awt.Color(255, 255, 255));
    ordem_servico.setPreferredSize(new java.awt.Dimension(1177, 746));

    jScrollPane1.setPreferredSize(new java.awt.Dimension(1177, 776));

    jPanel25.setPreferredSize(new java.awt.Dimension(500, 1000));
    jPanel25.setLayout(new java.awt.BorderLayout());
    jScrollPane1.setViewportView(jPanel25);

    javax.swing.GroupLayout ordem_servicoLayout = new javax.swing.GroupLayout(ordem_servico);
    ordem_servico.setLayout(ordem_servicoLayout);
    ordem_servicoLayout.setHorizontalGroup(
        ordem_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    ordem_servicoLayout.setVerticalGroup(
        ordem_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
    );

    rootDashboard.add(ordem_servico, "ordem_servico");

    dashboard.add(rootDashboard, java.awt.BorderLayout.CENTER);

    root.add(dashboard, "dashboard");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(root, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(root, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void ordem_servicoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordem_servicoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ordem_servicoButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
    UIManager.setLookAndFeel( new FlatLightLaf() );
    } catch( Exception ex ) {
        System.err.println( "Failed to initialize LaF" );
    }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new View().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cadastro;
    private javax.swing.JPanel dashboard;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JPasswordField jPasswordFieldSenha1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEmail1;
    private javax.swing.JTextField jTextFieldEmail2;
    private javax.swing.JPanel login;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel nameUser;
    private javax.swing.JPanel ordem_servico;
    private javax.swing.JButton ordem_servicoButton;
    private javax.swing.JPanel root;
    private javax.swing.JPanel rootDashboard;
    // End of variables declaration//GEN-END:variables
}
